title: "Sandra K. Chandy"
description: "Data Science · Machine Learning · Healthcare AI"
url: "https://schandy-25.github.io"
baseurl: ""

remote_theme: alshedivat/al-folio

# --- Author info ---
author:
  name: "Sandra Kettidathil Chandy"
  email: "sandrakettidathilchandy@gmail.com"
  github: "schandy-25"
  linkedin: "sandra-k-chandy-799486287"
  bio: "MS in Data Science @ Indiana University Bloomington | Healthcare ML | Graph ML | LLM Interpretability"

# --- Collections ---
collections:
  projects:
    output: true
    permalink: /projects/:name

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page
      nav: projects
      toc: false

# --- Markdown ---
markdown: kramdown
highlighter: rouge

# --- Optional site settings ---
plugins:
  - jekyll-sitemap
  - jekyll-feed

# --- Turn off avatar / photo ---
show_social_icons: true
show_author_profile: false
